### ISSUE TITLE
Changing to Integrated Only requires two clicks

### ISSUE THREAD

**Issue by iDontCYnot** [codykrieger/gfxCardStatus#103]
When using gfxcardstatus on a retina macbook, clicking 'integrated only' does no change the graphics settings and the tick moves back to 'dynamic only' almost instantly. Pressing 'integrated only' a second time does however activate integrated only

**Comment by bmacgreg312** [comment]
Hi,
I see this is an old issue - still going in 10.10.5 (mid-2010 MacBook Pro). The "discreet" card causes crashes, so being able to stay with the integrated one is a lifesaver. However, if I set it to "i" and then start Adobe Illustrator, it overrides that and switches back to "d". I have to quick shut down Illustrator, click on "integrated" again, and then it behaves for the rest of the day. Has anyone figured out a way around this?

**Comment by codykrieger** [comment]
@bmacgreg312: This is a different bug that only exists on 2011-and-newer MBPs. You're running into #107.

**Comment by bmacgreg312** [comment]
Okay, thanks. Sounds like there’s still no easy fix? I will try to remain vigilant…

On 13 Jun 2016, at 11:39, Cody Krieger <notifications@github.com<mailto:notifications@github.com>> wrote:


@bmacgreg312<https://github.com/bmacgreg312>: This is a different bug that only exists on 2011-and-newer MBPs. You're running into #107<https://github.com/codykrieger/gfxCardStatus/pull/107>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/codykrieger/gfxCardStatus/issues/103#issuecomment-225619552>, or mute the thread<https://github.com/notifications/unsubscribe/AS_SfcPbEJ3P1GKynL5QD4g3LvlbNTe-ks5qLXmWgaJpZM4ANPvU>.

---------------------------------------------
Barbara MacGregor
University of North Carolina
Department of Marine Sciences
3117C Venable Hall (a/k/a Murray)
CB#3300
Chapel Hill NC 27599

Email bmacgreg@unc.edu<mailto:bmacgreg@unc.edu>
Cell +1 (919) 260-6038
Fax +1 (919) 962-1254
Lab 3110 Venable Hall

**Comment by bigdoghat** [comment]
My computer also needs integrated to be selected twice and often during this the computer would freeze and crash then tries to repeatedly reboot on the dynamics card and I'd get the blue screen.

This workaround below has been doing well for me if I have the computer set to Integrated only and something happens that requires a reboot.  It gets my machine back up and running quickly without endless reboots and hoping each time that I don't get the blue stripey screen.

1) make sure gfx card status **isn't** set to fire up on computer boot up via the gfx prefs

2)  After the first reboot you'll probably get the blue stripey screen if you have the same issue as me, the fans will turn on high, leave it like this until the computer shuts itself down from getting too hot.  Immediately press the power button and turn the computer back on after the shut down.  I got this tip from elsewhere.  For some reason immediately rebooting after an overheat shutdown fires up the integrated card on the next reboot.  

3)  Delete your old copy of gfx card status and download a fresh copy.  Then do the double integrated click to switch to integrated only.  This has worked about 8 times in a row for me without fail.  For some reason using the existing copy of gfx card status will crash the computer when trying to switch to "integrated only" after reboot.  Deleting the existing copy and installing a fresh copy doesn't crash for some reason.

I'm sure this makes no technical sense but as I said, it's worked for me and I can get back up and running fast after a reboot.

I'm on a 2011 Macbook Pro running Mavericks 10.9.3

**Comment by codykrieger** [comment]
Tracking in #310; closing.
