### ISSUE TITLE
gfxCardStatus won't allow "Integrated Only" on Early 2011 MBP with dead GPU

### ISSUE THREAD

**Issue by ttrtilley** [codykrieger/gfxCardStatus#146]
Strangely enough, it DOES allow "Discrete Only" and also allows Dynamic.
I had to delete a couple .kext files to get it to boot all the way to login screen.
This problem also occurs when booted "Safe Mode".
I am still running Mountain Lion 10.8.5

ogattaz gives an excellent description of this problem in:

https://github.com/codykrieger/gfxCardStatus/issues/9

which I have embedded here:

 ogattaz commented 2 months ago
Today gfxCardStatus is used by a lot of the owners of early 2011 MBPs who have troubles with the external Radeon GPU.

Look at the thread https://discussions.apple.com/message/23685303?ac_cid=tw123456

For example, to be able to boot my MBP 8.2 , I must remove the ATI\* and AMD\* extensions, but in this case, the selected GPU is the Radeon GPU and gfxCardStatus is not able to force the usage of the integrated GPU because it detects an external display even I have no plugged external display !...

note: if I let the ATI\* and AMD\* extensions in place, my MBP freezes during the boot sequence

It would be great if we could use gfxCardStatus to always force the usage of the internal GPU.

**Comment by kwamayze** [comment]
1. Shut down the computer.
2. Plug in the MagSafe power adapter to a power source, connecting it to the Mac if its not already connected.
3. On the built-in keyboard, press the (left side) Shift-Control-Option keys and the power button at the same time.
4. Release all the keys and the power button at the same time.
5. Press the power button to turn on the computer.
The twist is in step 4. I held the keys in step 3. for about 5 seconds, then released all EXCEPT the power button, holding this for an additional 5 seconds before releasing it. Finally, step 5. The computer booted with a normal screen, which I hadn't seen in 2 months, BUT, the fans were going full blast, no led on the MagSafe, no battery in the menu bar, Mac not going to sleep when closing the top, and probably  other stuff that I missed.
I rebooted several times from the menu, without problem and with a normal screen, but still with the fans blasting and all…
Finally, I shut down and did a NORMAL SMC reset, the Apple standard way, and lo and behold… a normal startup, normal screen, fans, MagSafe, everything!
Seems to refresh the screen and continue where it would normally hang. Explanation welcome

**Comment by ElleLuca** [comment]
A genius bar rep suggested gfxCardStatus because my video card is bad and the system crashes before it completes the boot.

reading this post, the issue seems to be the same as the one reported by ttrtilley (and others).


I have the following questions for the author (and thank you for developing this software in the first place).



1. Is gfxCardStatus indeed a possible solution by forcing the use of “integrated only” early enough in the process to allow boot to complete?



2. I had previously found this online:  https://forums.macrumors.com/threads/force-2011-macbook-pro-8-2-with-failed-amd-gpu-to-always-use-intel-integrated-gpu-efi-variable-fix.2037591/page-57#post-25751208  where a manual procedur is posted. Are the two approached similar?



3. How can I install gfxCardStatus when I cannot get the machine to boot?

I have three suggestions: 
(i). Allow or install on in single-user mode (that works);
(ii) Allow for install in “target disk mode on another machine;
(iii) Allow for install on another computer even if that other computer is not a compatible machine (i.e. on an incompatible machine the software has no effect but it does allow for install and be ready to run when booting a compatible machine).


Thank you!
