### ISSUE TITLE
Reports of badness on 10.9.3+: active GPU + Dependencies list not updating, gfxCardStatus getting stuck as a dependency

### ISSUE THREAD

**Issue by codykrieger** [codykrieger/gfxCardStatus#162]

**Comment by Julianh22** [comment]
gfxCardStatus  won't let me switch to Integrated graphics saying that gfxCardStatus itself requires the use of the discrete graphics card. I see this problem has been reported before. Is there a fix?

![gfx message](https://cloud.githubusercontent.com/assets/12514907/7706510/1f33664e-fe4b-11e4-997e-0aec4baa755c.png)

I am using a 2010 Macbook Pro 15". These machines often had graphics card problems that surface after a few years of use. My machine shuts down unexpectedly. Apple is asking €650+ to replace the logic board, an unacceptable charge since the cards are known to be faulty. My interim (long term if Apple don't change their mind) solution would be to use gfXCardStatus to keep me on integrated graphics so that the faulty graphics card can't cause repeated machine shutdowns. But this can only work if gfx does not itself impede the selection of integrated graphics.

**Comment by codykrieger** [comment]
This issue is tracking that problem, as well as a couple others. There's no fix yet.

**Comment by Julianh22** [comment]
Thanks. Given that some earlier posts were July 2014 should I assume that nothing is going to happen? Or could a fix still be on its way?

**Comment by Julianh22** [comment]
It would be great if this could be sorted

**Comment by codykrieger** [comment]
I wouldn't count on it any time soon.

**Comment by Julianh22** [comment]
Understood. Thanks

**Comment by davidham** [comment]
Hi Cody, do you know of any workarounds for this? I'm getting GPU panics on my mid-2010 MBP and google searches led me to your excellent utility. I plan to upgrade to a new laptop soon but I'd love to stop the panics on this machine in the meantime if I can. I'd be grateful for any advice you can offer. Thanks!

**Comment by Julianh22** [comment]
I don’t know if this helps but I had what might have been a similar problem on my mid-2010 MBP. In this case the problem turned out to be a faulty GPU. Apparently this was a regular problem and Apple provided had a free replacement programme for these faulty GPUs. When I brought my problem to Apple’s attention they kindly informed me that the programme had terminated and so I would have to pay for the replacement GPU. We had a nice little discussion. I explained that an inherently faulty GPU is inherently faulty regardless of whether the fault manifests during or after their free replacement programme. After a bit of escalation to the relevant manager and referencing the information that confirmed that this was accepted by Apple as a “their fault” problem Apple fitted a new GPU. Since then I have had no further problems.

I can’t reference the specific web pages that detailed this problem but some google searching should locate it for you.

I hope that helps

Julian

**Comment by davidham** [comment]
Thanks Julian! Do you have a URL for the 'their fault' info that you spoke of?

**Comment by Julianh22** [comment]
David

Have a look at this one. It’s not the article itself but the comments at the bottom that helped me

http://www.macworld.com/article/2062783/cures-for-a-panicking-mid-2010-macbook-pro.html


I can’t find the details of the recall and replace programme that Apple were running but it must be somewhere on the web. Just like some of the comments on this thread, at GPU test showed the GPU to be faulty. If my memory is correct, Apple had to replace the CPU as well because they are all on the same integrated board.

Sorry I haven’t got any more information. 

My best suggestion would be:

look through all the comments on the link I have given you
look up mid-2010 macbook GPU problems (or something similar) to see what more you can find
take the Mac into an Apple store. They should be able to run a test to check out the GPU. If it’s faulty you can ask them to find details of the recall programme and have a friendly discussion about why you should not have to pay for fixing something that was faulty when it was sold

And of course it is possible that your problem is not the same as mine, though it sounds very likely that it is.

Hope that helps

Good luck

Julian

**Comment by steveschow** [comment]
apple is no longer helping anyone with 2010 machines.  Most of the Apple links on the net that used to say so have been taken down too.  Also some people that had it done said that eventually the GPU started failing again, sometimes within 6 months.  We're barking up the wrong tree, Apple isn't going to help with this now.

**Comment by codykrieger** [comment]
Tracking in #310; closing.
