### ISSUE TITLE
Changing to Integrated Only from Dynamic distorts the image on screen

### ISSUE THREAD

**Issue by emolano** [codykrieger/gfxCardStatus#199]
I'm in a Late 2010 MBP with GeForce NVIDIA GT 330M and using gfxCardStatus 2.2.1. When changing from dynamic to integrated only, it always changes to Discrete only. When clicking  a second time to Integrated only, sometimes works and sometimes create a distortion on screen. When clicking back to Discrete Only, images gets fixed. I started using gfxCS as i was having random black screens with CPU panic.

**Comment by codykrieger** [comment]
The latest version, v2.3 (released some two years ago, if I'm remembering correctly), does not have this problem. Visit https://gfx.io to download it.

**Comment by emolano** [comment]
That's great...but does it run for MacOs 10.6.8?? I don't want to upgrade to 10.7 for some specific software i use for work.

**Comment by codykrieger** [comment]
Snow Leopard was released almost six years ago, and there have been four new major releases since then. It's an incredible burden to support operating systems that old, and you are leaving yourself open to gaping security holes by running such old software that is no longer being supported or updated.

Please upgrade to Yosemite.
