### ISSUE TITLE
unable to build project

### ISSUE THREAD

**Issue by steveschow** [codykrieger/gfxCardStatus#229]
I followed the instructions in the read me.

`git clone --recursive git://github.com/codykrieger/gfxCardStatus.git`

Open the project in Xcode 6.2, attempt to build it, get the following linker error:

`ld: library not found for -lPods-gfxCardStatus-JRSwizzle
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by CarlQLange** [comment]
Same here.

**Comment by steveschow** [comment]
I was able to get the debug version to build, but not release as of yet.  Basically there is a sub project that needs to be built, which appears to be not configured to do so in the main Xcode project.  I don't know that much about Xcode, so this is straining my brain to figure out honestly, but if you go into the Pods sub folder you will see an Xcode project.  Open it and build it as DEBUG.  Then go find the library binaries it builds and copy them into the DEBUG destination for gfxCardStatus.  There are four of them:

`libPods-gfxCardStatus-JRSwizzle.a
libPods-gfxCardStatus-libextobj.a
libPods-gfxCardStatus-ReactiveCocoa.a
libPods-gfxCardStatus.a`

After that go back to the main gxCardStatus Xcode project and build DEBUG.  Worked for me.   However it did not work for me on the release build, I got some errors about some kind of another incompatible lib, I will try to figure out later when my brain doesn't hurt.

I think probably the main gfxCardStatus Xcode project needs to be updated to included information about the sub project, both how to build it first, as well as included the lib binaries in the library search path for the main app build.

I also disabled the code signing at some point while I was trying to figure this out because I was getting errors about that, and will have to go back to scratch to see if it would hypothetically build without turning that off.

**Comment by steveschow** [comment]
this is the error when trying to build release version in case anyone knows solution:

> error: -fobjc-arc is not supported on platforms using the legacy runtime
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

i get the same error while trying to build the Pods subproject as release also.

**Comment by socketbox** [comment]
Hi Steve,

This is probably a little late to be much help to you, but maybe someone else who happens upon this will get some use out of the instructions below. Caveat: it's a case of the blind leading the blind, as I've got very little Xcode experience myself, but I was able to build the project and get it to run on my machine, as well as create an app archive...as usual, take what you need and leave the rest.

NB: I'm running XCode 7.3.1 under 10.11.5 on an early-2011 MBP 15" 

At any rate, here's what I did:

1. Installed [Cocoapods](https://cocoapods.org/) using [Homebrew](http://brew.sh/)
1. `git clone https://github.com/codykrieger/gfxCardStatus.git`
1. `cd ./gfxCardStatus`
1. `pod update`
1.  Opened XCode and from File menu, chose Open... and selected the `gfxCardStatus.xcworkspace` file (**not** the `.xcodeproj` file)
1. With gfxCardStatus selected in the Project navigator, set Deployment Target (under the General tab/screen) to the desired version of OS X 
1. In the Code Signing section of the Build Settings tab, selected _Don't Code Sign_ for Release
1. In the Issue navigator, under the gfxCardStatus.xcodeproj item, selected _Update to recommended settings_, then chose _Perform Changes_ and _Continue_
1. In the root of the project, from the command line, run `xcodebuild -workspace gfxCardStatus.xcworkspace -scheme gfxCardStatus`
1. In XCode, under Product, choose Clean.
1. Under the same Product menu, choose Build.
1. Now, under `./build`, I've got a `Release` directory and a `gfxCardStatus.build` directory. The `Release` dir contains an app archive

**Comment by socketbox** [comment]
Late to the party, but maybe someone else who happens upon this will get some use out of the instructions below. **Caveat:** I've got very little Xcode/Obj-C experience.

NB: I'm running XCode 7.3.1 under 10.11.5 on an early-2011 MBP 15" 

At any rate, here's what I did. Again, I'm not at all sure if I've gone in the right direction, because some of the changes I've made were quite drastic in terms of dependencies. I hope that someone with more knowledge who's following the project will point out my mistakes.

1. Installed [Cocoapods](https://cocoapods.org/) using [Homebrew](http://brew.sh/)
1. `git clone https://github.com/codykrieger/gfxCardStatus.git`
1. `cd ./gfxCardStatus`
1. Edited the [Podfile](https://github.com/socketbox/gfxCardStatus/blob/master/Podfile) such that ReactCocoa was brought up to its latest version (4.2.1) and that libextobjc was eliminated as a pod (I add it back later as a git submodule).  
1. `pod install`
1. `git submodule add https://github.com/jspahrsummers/libextobjc.git`
1.  Opened XCode and from File menu, chose Open... and selected the `gfxCardStatus.xcworkspace` file (**not** the `.xcodeproj` file)
1. With gfxCardStatus selected in the Project navigator, set Deployment Target (under the General tab/screen) to the desired version of OS X. Repeated same with Pods project selected.
1. In the Code Signing section of the Build Settings tab, selected _Don't Code Sign_ for Release (NB: do this as well for the Target of gfxCardStatus while you're in Build Settings)
1. In the Architectures section of the Build Settings tab, selected _Standard Architectures (64-bit Intel)_ for Architectures; eliminated _i386_ as a Valid Architecture in same section. Repeated the same procedure with Pods project selected.
1. In the Issue navigator, under the gfxCardStatus.xcodeproj item, selected _Update to recommended settings_, then chose _Perform Changes_ and _Continue_
1. Checked the Deployment section of Build Settings tab once again, for both projects, in order to ensure that the value selected jibed with that chosen earlier.
1. Edited `[GSMenuController.m](https://github.com/socketbox/gfxCardStatus/blob/master/Classes/GSMenuController.m)`, `gfxCardStatusAppDelegate.m` such that `rac_signalForKeyPath` is no longer called, but rather `rac_valuesForKeyPath`. 
1. Once again, ensured that _Don't Code Sign_ is configured for all projects and targets (there's got to be a less tedious way of changing the same flag across all configurations).
1. Product menu, Clean.
1. Product menu, Build.
1. Product menu, Archive.

Hope this helps.

**Comment by codykrieger** [comment]
Tip-of-tree gfxCardStatus now builds like a champ—just open the .xcworkspace and hit ⌘B.
