### ISSUE TITLE
Switching to Integrated Only switches to Discrete Only

### ISSUE THREAD

**Issue by fishcharlie** [codykrieger/gfxCardStatus#242]
Switching to Integrated Only switches the setting to Discrete Only but continues to run on the integrated GPU.

**Comment by codykrieger** [comment]
I suspect this is #103.

**Comment by fishcharlie** [comment]
@codykrieger Not really. Even after clicking "Integrated Only" multiple times it still goes to "Discrete Only". Even if originally start on "Dynamic Switching" OR "Discrete Only".

**Comment by fishcharlie** [comment]
Going to continue to look at the code and try to come up with a solution and if I find one I will submit a pull request. But not sure if I'm going to be able to find it. So any tips or extra information please post here :)

**Comment by grgarside** [comment]
Upon clicking Integrated Only, it seems like Integrated Only is set, as opening an app such as FCPX doesn't engage discrete graphics. However, when quitting FCPX, upon which in dynamic switching the discrete would be disabled, discrete graphics are _enabled_ and Dependencies are shown as None.

**Comment by codykrieger** [comment]
@grgarside 2010 MacBook Pro?

**Comment by grgarside** [comment]
@codykrieger mid 2012 Retina MacBook Pro

**Comment by codykrieger** [comment]
Huh. Then it seems like the workaround I was using on 2011-and-newer MacBook Pros no longer works.

**Comment by MacDragon** [comment]
Definitely something odd going on. Current version for me on a mid 2015 15" pro generally switches to discrete only on the menu when selecting integrated, though the actual gpu doesn't switch till called for still.  Trying it enough times, it does eventually manage to stick and work, but can't see any obvious consistency in it.

**Comment by truth1ness** [comment]
This just started for me, once in a while opening or closing a program that uses discrete will override my Integrated Only preference and I have to quit and change it back.

**Comment by codykrieger** [comment]
@truth1ness That's #107.

**Comment by steveschow** [comment]
truth1ness, try my fork: https://github.com/steveschow/gfxCardStatus/releases

**Comment by dfjdejulio** [comment]
FYI, this started happening for me on a mid-2012 non-retina MBP upon upgrading to Sierra.  The I click on "integrated only", the check appears next to "discrete only", the icon stays as an "i" instead of a "d", and it tells me it's using the Intel GPU and not the NVidia one.

Before upgrading, I *was* having issue #103.

**Comment by brumbrumbrumbrum** [comment]
@codykrieger Hi, i have a mid-2012 rMPB and the same issue, when i select "integrated only" the GPU changes into HD4000 but the stat stay fixed on discrete only (while icon say "i");
- Anyway the issue behaves like an "evolution" of the #103: if you first select "discrete only" and then double time on "integrate only" the stat return to works. Note that if you have already select "integrate only" you have first to select "dynamic switching" and then "discrete only".

**Comment by steveschow** [comment]
Please try this new release, should fix the menu problem:

https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.2i

**Comment by steveschow** [comment]
https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by steveschow** [comment]
Please try this and let me know if you have any problems: https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by szhorvat** [comment]
@codykrieger Regarding the problem where it switches to the discrete GPU even if the integrated one is selected: #107 seems to be a very old bug but this problem only started for me after the Sierra upgrade.  (Mid-2014 MBP with NVIDIA GT750M)

**Comment by sikaco** [comment]
@steveschow 
My macbook is mid-2015 with AMD graphic, I find that if external display was connected, gfxCardStatus will change to discrete card. Except for that everything is perfect. 

Actually, this "feature" also good. I just be curious about know it is a "feature" or a "bug"?
THX much~

**Comment by caratulon** [comment]
Thanks a lot, v2.43i is working on mbp retina late 2013 nvidia 750m using Sierra 10.12. However, for me the main use is  force integrated intel cart load  when I'm booting arch-linux. This version no work for that. I restart with the  integrated card working, however on boot does not load the intel card. Using El capitan 11.10 version with gfcard  v2.2.1 works perfectly. Actually I'm booting with usb el capitan then I'm booting the arc- linux with integrated card. I'm wondering if you can fix that.

**Comment by Arfius** [comment]
MacOS Sierra
gfxCardStatus v2.3

When I click on 'integrated only mode' , I get 'Can'tSwitchToIntegratedOnlySingular'  , gfxCardStatus stops itself. 
![schermata 2016-11-09 alle 17 05 34](https://cloud.githubusercontent.com/assets/665555/20145117/20dd90fc-a69f-11e6-84f3-508a8843b651.png)

**Comment by bednarikjan** [comment]
@steveschow Your adjusted version of gfxCardStatus v2.4.3i resolved this issue for me on MacBook Pro mid 2015, thanks!

**Comment by hohl** [comment]
2.4.3i works for me

**Comment by agoston** [comment]
2.4.3 works on a 2011 MBP (discrete GU dies just after 2 months of Apple's 2016 December deadline for return for repairs... grrr....)

**Comment by roboknight** [comment]
@agoston Yeah, I pretty much had the same thing happen.  And, worse yet, Apple won't fix it claiming they no longer have the parts to do so (possibly true, but who knows the truth but them).  At any rate, I can't get v2.3 to switch to integrated graphics as it continues to claim I'm using an external monitor.  I don't know if that's because I had to move the driver (after going to target disk mode and using my wife's Mac because Sierra won't let you move any files if you can't boot into Recovery mode, which I couldn't, to turn off rootless.  Thanks Apple for locking me out of my machine completely...).  So now I'm using the discrete chip with slow graphics, and I don't know if I can even USE the integrated chip.

**Comment by agoston** [comment]
@roboknight I guess the time is now then to get a chromebook for a few hundred bucks. The specs are similar, often better. I just didn't want to throw a perfectly good functioning machine in the garbage.

**Comment by iceman60** [comment]
Same problem for me on a MBP 17" Late 2011! But I tried to activate the discrete mode only to be sure and it's not booting anymore... Someone know how to roll back in safe mode? This IS the only way I can boot, even with Sierra installer key I got the grey screen :/

**Comment by roboknight** [comment]
@iceman60 The way I finally did it for Sierra was to go to target disk mode and use another mac in order to move the driver in /System/Library/Extensions out of the way.  I have the AMD chip, so I had to move AMD* to another directory (don't delete them, if you do manage to get a new chip somehow, you won't want to reinstall the OS).  Once you do that, you'll be able to boot, albeit in a horrible semi-low-res mode that is really "slow" (the graphic effects are "visible" and the mode is low res, so while somewhat useable, it won't be anywhere near ideal for watching movies or anything, but will let you back up and get to a state where your data is safe).  If you don't have another machine, I'm not sure what to tell you because I was basically stuck.  I tried EVERYTHING, including a few boot options to try to get it to use the internal graphics, but I don't think it is possible.  You still won't be able to boot to recovery, because recovery uses the same driver (unless you also go to the recovery partition and move the driver there also).  I would give you more details, but I'm not sure how tech savvy you are and I'm pretty terrible with directions.  There are other places on the web where people did the same thing in the past (before Sierra, but easier) and usually they will detail the process for you if you need it.

**Comment by iceman60** [comment]
@roboknight Moving AMD Kext to another folder didn't wake up my Mac, I got grey screen again... I'm not able to launch Sierra installer on USB key, I'll try to open the package and find AMD Kext to delete them before booting on my key but doubt it will work. So, now I have a nice big brick that cost more than 4000$, thanks Apple!

**Comment by agoston** [comment]
Mine also didn't even get past the apple logo, but I tried the idea on the net where you disassemble the logic board and apply 120-160 celsius degrees temperatures with a heat gun. While there, also re-greased the cpu + gpu with a proper arctic silver thermal grease.

This would make it come back to life for a bit more (note, everyone agrees this is a temporary hack only).

Once you get up and running, disable the discrete GPU and don't reboot. I've used gpu-switch to execute it on startup (from crontab).

My hope is that
- with the discrete GPU disabled, the CPU will not generate enough heat to make the GPU relapse;
- even if the GPU breaks again, cpu would be able to boot up and then gpu-switch would switch to integrated-only;
- I don't have to reboot too often -- just close the lid and don't update.

Chances are, it would still brick soon, but it's something I wanted to try before putting it in the dump. There is a chance that it would keep working for a few years more, which is just enough.

And yes, Apple sucks.

**Comment by matanglawin** [comment]
@codykrieger My MBP Early 2011 has had its logic board replaced before the program expired in 2016.  Then it was really bad, since I couldn't start the MBP up at all.  

A couple of months ago, it started giving out again, even though the AHT didn't register anything wrong with the hardware, I was sure it's the same graphics card issue.  I found your fix, tried it, and it worked every now and then.  I've had this issue of switching to discrete first, then only to integrated the second time round, and then sometimes, it will switch to integrated right away, but, the MBP will hang, forcing me to do a hard-restart.

I tried both versions of @steveschow fix, but, that didn't work at all. Simply clicking to switch the GPU freezes everything.  

I kind of figured Battery Helper, which starts up during login, might be a factor, to I uninstalled it.  I also uninstalled Steve's versions, then reinstalled 2.3, without having it launch at login.  Right now, whenever I'm forced to restart (and it's taking quite longer each time I have to), I'll just launch 2.3 and switch to integrated without a hitch.

Then, I realized I can't launch any Adobe application without the computer freezing, so I was forced to just use the MBP for browsing and watching videos.  I didn't have projects anyway, so it's not so much an issue, except if I really needed to use Illustrator or photoshop to do a quick graphic.

While browsing the issues here again for the nth time, I saw one of your comments about fiddling with the Energy Preferences setting.  Earlier on, I do switch that to "Better Batter Life" each time I switch to integrated, and when I did, I was able to launch and create a new document in Illustrator.

I'm not a programmer though I did a little bit of coding back then), so I have no idea if that is significant.

I am planning to get a new MBP soon, and will have my current one undergo that reflow fix.

**Comment by roboknight** [comment]
This solution was pretty effective: https://forums.macrumors.com/threads/force-2011-macbook-pro-8-2-with-failed-amd-gpu-to-always-use-intel-integrated-gpu-efi-variable-fix.2037591/ ... It forces the GPU to be integrated from boot and will not switch back unless you clear your PRAM or possibly an update (if that clears PRAM).  Note that before I even found this solution to the problem, I had pretty much moved the graphics driver out of the way and had a booting system because it wouldn't send the Discrete graphics chip into a mode where it would hang.  But it left me booting with vertical bars.  So I knew it was still using the discrete GPU, but it was very slow and the system was pretty unusable.  The above fix *SHOULD* work without having to move the graphics drivers or any of that nonsense as it sets an EFI variable.  Without this, I don't really think it is possible to control the GPU anymore like it was on Snow Leopard, or even Lion maybe.  At any rate, I thought I'd put this here because I only found it by accident because some YouTube video showed up somewhere and I clicked on it and found these instructions and tried them.  I reviewed the same script the guy posting the instructions talks about and basically the instructions are walking you through the script, because likely the script doesn't run for some reason or other.  At any rate, it should get you to integrated only graphics.  Power on, power off, do what you like without clearing the PRAM and you're good to go.  One more note:  I don't think the version of Arch Linux matters, but the ISO he used isn't available anymore.  But I think if you use the latest, you'll be fine.

**Comment by roboknight** [comment]
@Iceman60 -- I should have tagged you in the above solution because this is what you and I were BOTH looking for back then... I only found this a few weeks ago.

**Comment by whaleyland** [comment]
It doesn't look like the original problem was ever actually resolved. I've got an early 2017 MacBook Pro running Intel Graphics HD 530 and AMD Radeon Pro 460. Whenever I select "Integrated Only", "Discrete Only" is selected and multiple clicks of "Integrated Only" does nothing. As reported above, it doesn't actually switch to the AMD card, but it will automatically switch when I open apps that "require" discrete, such as Google Chrome.

Has there been any solution to this? My only 2011 MacBook Pro fried its discrete graphics card and I am trying to avoid it on this computer by only using it when necessary, but that's hard to do when I can't manually manage use of said card.

**Comment by matanglawin** [comment]
@whaleyland Try the [GRUB] fix.

https://forums.macrumors.com/threads/disable-a-failed-amd-gpu-on-a-2011-macbook-pro-grub-solution.2087527/

**Comment by matanglawin** [comment]
@whaleyland The grub fix works just fine with me, although, I didn't know that the 2017 MBPs would have the same GPU issues as the older MBPs, so I'm not sure why you need keep your MBP on iGPU.

**Comment by whaleyland** [comment]
I think you're misunderstanding me. I want gfxCardStatus to be able to switch the GPUs on my early 2017 MacBook Pro and it currently isn't working. Re-read the first paragraph in my comment above and just ignore the second. More generally, I want gfxCardStatus to work on my early 2017 MacBook Pro because I suspect what happened to my earlier computer will happen again in 3-5 years and I want to head that off by limiting my use of the discrete GPU. gfxCardStatus is worthless to me if it cannot actually control which GPU is being used.

**Comment by matanglawin** [comment]
I did not misunderstand you.  Regardless of your intent, or whether the new models will have the same dGPU issues, it's rather clear that the gfxcardstatus is not working on the 2017 models.

**Comment by codykrieger** [comment]
Tracking in #310; closing.
