### ISSUE TITLE
"GfxCardStatus" is damaged and can't be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by The-Dread-Pirate-Roberts** [codykrieger/gfxCardStatus#245]
I've tried to DL this several times now with this same result...
I found where some other user had reported the same problem and your solution was:

"Unzip the gfxCardStatus download with OS X's built in Archive Utility, not The Unarchiver or 7-Zip."

Unfortunately, that doesn't help me because the Archive Utility is my default and it what I am using...

Other ideas..??

**Comment by codykrieger** [comment]
I just verified that it works as expected on El Capitan—no issues to speak of. Is your system clock way off or something? OS X will say the app is “damaged” if it's unable to verify the code signature. Maybe check Console.app for interesting messages around the time you try to open the app?

Closing since this doesn't seem to be a systemic issue of any kind.
