### ISSUE TITLE
Re: locked issue #240 - macOS 10.12.3 now out with bugfix from Apple!

### ISSUE THREAD

**Issue by SteveJobzniak** [codykrieger/gfxCardStatus#266]
Great news! I never thought we would see the day of Apple caring about their older hardware, but here it is!

http://forums.macrumors.com/threads/warning-bugs-in-sierra-which-affect-all-macbook-pro-2010-models.2000559/page-3#post-24237506

**Comment by maciboy** [comment]
Great!
I also received good news directly from Apple's developers:
After deactivating Siri with 10.12.4 'SiriNCService' will not longer block the switching back to integrated graphics. 
I tested it on MBP 2010 15': approx. 1 minute after ending interaction with Siri gfx tells that the graphic is changed back form Nvidia to Intel 😀

**Comment by SteveJobzniak** [comment]
@maciboy Isn't it amazing?! Apple actually cares about our older laptops! Oh thank god for that Siri fix too! WOW!

I've been running my ugly hack (⇧⌥⌘Z) to run a script that kills SiriNCService. Had to press that every time. I really look forward to 10.12.4 now so I can throw out that hack!

**Comment by maciboy** [comment]
I called my script „Kill Siri“ and made an app out of it. So what I said to Siri, when I wanted the conversation to end, was: „Kill Siri“ 😆

I’m also really amazed why Apple cares after letting us alone for so many years.
Maybe it is the last OS our machines will officially support, so they make sure that everything works fine? Who knows…

However, I was wrong that SiriNCService gets killed after a certain amount of time. It seems as if an interaction with an other app is necessary to trigger the change:

If one ends Siri and then just waits, nothing will happen. One can wait for ages and Intel graphics will never be reactivated.
The change happens when one e.g. opens an other app or clicks in an other window.
I wonder why it is like that and posed this question to the developer who send me the feedback, maybe we will get an answer. Nevertheless, already this new way of ending Siri is great :)

**Comment by maciboy** [comment]
Please leave it at least open for further discussion :/

**Comment by codykrieger** [comment]
This is not a forum—it's a place meant for reporting issues with gfxCardStatus.

**Comment by SteveJobzniak** [comment]
@maciboy 

> Maybe it is the last OS our machines will officially support, so they make sure that everything works fine? Who knows…

Sad but possible. But we can always hack its .plist to let it install, like some already had to do with Sierra on older machines. Our machines will support macOS for like another decade at least.

> I wonder why it is like that and posed this question to the developer who send me the feedback

Great. Thanks for the work you are doing. :)

**Comment by SteveJobzniak** [comment]
@codykrieger And that's what I did with this ticket. Hi, welcome back.

**Comment by codykrieger** [comment]
@SteveJobzniak ...in what way were you reporting a gfxCardStatus issue when you opened this ticket?

Please don't waste my time and fill my inbox by abusing GitHub's issue tracking mechanism as a forum.
