### ISSUE TITLE
High Sierra - 10.13 - IOFramebuffer.cpp - mentions gfxCardStatus

### ISSUE THREAD

**Issue by nsgrbr** [codykrieger/gfxCardStatus#296]
I do not know if this will influence any version of gfxCardStatus in High Sierra 10.13.

High Sierra - 10.13 - IOFramebuffer.cpp - mentions gfxCardStatus:

https://opensource.apple.com/source/IOGraphics/IOGraphics-517.17/IOGraphicsFamily/IOFramebuffer.cpp.auto.html

    /*
     <rdar://problem/33240449> 17A306d : Coin Flip app and gfxCardStatus go not responding, stuck in IOFramebuffer::_extEntry()
     When extCopySharedCursor() was introduced, the usage of extEntry/extExit was added.
     For now, comment these out and return to the previous functionality and
     lack-of-locking while maintaining the structure and usage of extCopySharedCursor().
     */

**Comment by codykrieger** [comment]
That is high-larious. Thanks for the tip!

**Comment by caiceA** [comment]
@codykrieger just to clarify is this workable for me? 
Is your gfxcardstatus software Works for MacBook pro 2016 touch bar OS 10.13 high sierra and my computer which has dual graphics cars ie. I have built in intel HD530 +  4gb Radeon Graphics Cards 460 will your software work for me to increase the battery life?

**Comment by caiceA** [comment]
why did you remove my comment instead of answering it? is it workable for MBP 2016 / Touch one? @codykrieger

**Comment by codykrieger** [comment]
@caiceA Because you emailed me the same question at the same time as you posted your comment, which is unnecessary spam in my inbox, and you’ve commented on an issue totally unrelated to the question you are asking.

GitHub issues are not the place to ask questions like this.

**Comment by caiceA** [comment]
@codykrieger my email is like GMX (unusual) which normally goes to spam box it not in my hand.. but can you please answer me through email? i will be grateful to you !!!

**Comment by varunsinghal2311** [comment]
@codykrieger can you please anser this?

I have 2011 15 inch macbook pro (A1286). i had the same GPU problem in 2016 and got the MBP motherboard replaced under the apple exchange program. Since then the mac is running perfectly fine, with no issues at all. As said by many experts that Apple has replaced the faulty logic boards again, the replaced ones are also bound to fail. So should I perform this MOD before my GPU(AMD) fails or should I wait for it to fail?
Would I be able to perform these steps once GPU fails?

someone suggested me to use gfxcardstatus for integrated mode. do you think that will help me to stop wear and tear of AMD GPU thereby preventing any failure?

**Comment by codykrieger** [comment]
@varunsinghal2311 I honestly don't know. I don't have any first-hand experience with newer models of dual-GPU MacBook Pros.
