### ISSUE TITLE
Update documentation / expected to work on newer macs?

### ISSUE THREAD

**Issue by jjb** [codykrieger/gfxCardStatus#332]
For years I thought that this wouldn't work on my mid-2014 retina 15", but I just tried it and it does!

Should the website and read me be updated?

Or is it not really fully working?

**Comment by codykrieger** [comment]
@jjb The website hasn't been updated in some time—but then again, neither has the app itself. With every new macOS release, gfxCardStatus works a little more poorly than it used to.

When the 2010 MacBook Pros initially came out, the automatic graphics switching feature was incredibly aggressive due to the fact that the Intel GPU driver was never finished, so beyond basic 2D stuff, the NVIDIA GPU was needed very frequently. Naturally, that had a pretty noticeable effect on battery life, and that's why I ultimately created gfxCardStatus.

These days, the hardware and the software involved in automatic graphics switching is pretty good, to the point where most people shouldn't need to care which GPU is in use. There are still an awful lot of people with old/flaky hardware that use gfxCardStatus, but I don't recommend its use for most “normal” situations anymore.

**Comment by jjb** [comment]
ah, gotcha. thank you for the fast and thorough response!

another issue/datapoint sort of related to the above:  I'm pretty sure what's been happening with me is that for years my mac _never_ switched to the integrated gpu, even though there were no apps requiring it shown in activity monitor. yesterday i installed gfxcardstatus, and now my mac is switching back and forth normally (discreet for final cut, back to integrated when i quit it). even after i quit gfxcardstatus.

is it possible that at some point in the past, i was using gfxcardstatus, it had `setMode:GSSwitcherModeForceDiscrete` set, and then it got quit/killed and my machine was forever stuck in that state?

(thanks for any thoughts you might have on this- i'll submit a PR for the readme)

**Comment by codykrieger** [comment]
@jjb When gfxCardStatus quits normally, it sets you back to Dynamic Switching (i.e. re-enables “Automatic graphics switching” in System Preferences > Energy Saver). It's possible that if you had gfxCardStatus set to Discrete Only and then force quit it, you could have been left in that state, but getting out of it would have been as easy as ticking the “Automatic graphics switching” checkbox in Energy Saver preferences.

Perhaps you'd simply unchecked that checkbox in Energy Saver preferences at some point in the past?

**Comment by jjb** [comment]
Thanks for the followup. I've definitely unchecked and rechecked that box many times over the years. And i'm 95% sure my mac has been stuck in Discrete for years. 🤷‍♂
