### ISSUE TITLE
New User using a late 2011 MBP, 10.13.6, and gfxcardstatus 2.5

### ISSUE THREAD

**Issue by lalicatala** [codykrieger/gfxCardStatus#365]
1. I am seeing frequent crashes that lead to the gray screen of death that in multiple languages says you have crashed. Based on other t/s, it appears that this is a graphics chip issue, but which one, I cannot tell.

2. I cannot seem to get gfxcardstatus to stay in "discrete" mode. After every crash, user selected restart / shutdown, gfxcardstatus is dynamic user. So, how do I get it to stick in discrete mode???

3 When I finally do get gfxcardstatus in discrete mode, if smarticons is selected, the menu app becomes an script "a."  If not,  a plaintext "d."  I am unsure which preference I should select as "a" for discrete mode does not make much sense to me. Is there a preference as to which to select to minimize crashes?

4. Unable to select Integrated only mode no matter how many times I click on it. In safe mode, I can select it and the notification says I am running on the Intel chipset. Restarting in normal mode gets it back to dynamic. When I select discrete, the notification states I am now "hard wired" to using the AMD chipset.  Does this all mean that my intel chipset is bad? I have read #310 but am not savvy to enough to know if my issue is included with the issues in that report.

If in fact it is my AMD chipset, has anyone found someone that can successfully replace it? It appears that a late 2017 or later version of the AMD chipset can make this problem depart forever. A new motherboard was installed by Apple in 2016, 5 years after the first failure, here comes Failure #2.  A used motherboard is currently cost prohibited.

I know the Mac is old. I just need it to last until the Apple chipset MBP comes out, which probably is a year.

Thank for listening and your help.

**Comment by codykrieger** [comment]
Hi @lalicatala,

Lots to unpack here.

> 2. I cannot seem to get gfxcardstatus to stay in "discrete" mode. After every crash, user selected restart / shutdown, gfxcardstatus is dynamic user. So, how do I get it to stick in discrete mode???

gfxCardStatus always defaults to Dynamic Switching at startup—that's expected behavior.

If you want the machine to always use the discrete GPU, you don't need gfxCardStatus at all. You can quit gfxCardStatus, trash it, go to System Preferences > Energy Saver, and uncheck the _Automatic graphics switching_ checkbox. While gfxCardStatus is running, it manages that checkbox for you, so be sure to quit and delete gfxCardStatus first if you decide to go that route.

> 3 When I finally do get gfxcardstatus in discrete mode, if smarticons is selected, the menu app becomes an script "a." If not, a plaintext "d." I am unsure which preference I should select as "a" for discrete mode does not make much sense to me. Is there a preference as to which to select to minimize crashes?

The “smart menu bar icons” setting is a (poorly-named) legacy setting that just changes the icon that you see in the menu bar depending on which GPU brand you have. With that setting disabled, it's `i` for integrated and `d` for discrete. With the setting enabled, it's `i` for Intel and `a` for AMD (or `n` for NVIDIA).

> 4. Unable to select Integrated only mode no matter how many times I click on it.

This is #310.

I don't have any particular suggestions other than to try to hold out a little longer until the new machines come out.
