### ISSUE TITLE
Doesn't detect my two GPU's

### ISSUE THREAD

**Issue by dpsk** [codykrieger/gfxCardStatus#70]
Hello, i have 2010 MacBook Pros with Intel HD integrated and NVIDIA GeForce 330M GT discrete GPUs, which should be supported, however after updating to version 2.1. At startup app displayed "You are using a system that gfxCardStatus does not support. Please ensure that you are using a MacBook Pro with dual GPUs." Could you please give me a hint what im doing wrong?

**Comment by SteveJobzniak** [comment]
I experienced it too. It worried me so I looked in System Information and noticed that the system only saw my GT330M, and didn't see my Intel HD at all (weird, since the Intel one is inside the CPU).

It happened after my computer was restarted, so I think it's a matter of the Intel GPU very rarely not being initialized at bootup. First time I ever saw it.
