### ISSUE TITLE
Black screen with flickering on top on MacBook Pro 6,2

### ISSUE THREAD

**Issue by markusheiden** [codykrieger/gfxCardStatus#77]
With version 2.2.1 of gfxCardStatus I got a black screen with a small flickering bar on the top. I am using a MacBook Pro 6,2 with a GeForce GT 330M with 512MB VRAM. Version 2.1 works fine.

**Comment by theblizzardofoz** [comment]
Hi I might be all alone in my issue as I have a MBP 2010- 6.2 - 15" running yosemite. I had never heard of the logic board issue before :( I had no idea because I had not upgraded and was running snow leopard until just recently and of course as soon as I upgraded the problem reared its ugly head. I have no idea what version of gfxCardStatus I should be using for my model??? I just tried using gfxCardStatus v2.3   and even though I have it set on (discrete only) it continuously changes modes anyways??and have had a few crashes already, are their additional steps or add ons I need to take? or add something else to the mix? Pretty shocked to find out I could have had a free fix but didn't know I had a defective MBP until it is now way too late. Help! Thanks in advance :)

**Comment by codykrieger** [comment]
@theblizzardofoz At this point, with a machine that's approaching six years old, I'd recommend just getting a new machine.

**Comment by theblizzardofoz** [comment]
man..really? a $2500 purchase used for 2yrs...useless now :( they say they'll fix it for $646 but I read it doesn't even guarantee the logic board won't fry again

**Comment by glaszig** [comment]
@theblizzardofoz you purchased a 3 year old machine for 2500 bucks? 
anyway, a few days ago i was on the phone with an AASP guy who was still talking about that recall option. i'm not sure if he was up to date but i'd recommend you go to a genius bar and tell them exactly that. even better might be to send it in for repair via the support section on apple.com. i've heard (and this is unconfirmed) that send-in-repairs might be more graceful.

**Comment by theblizzardofoz** [comment]
@glaszig bought brand new in 2010,,used for 2 yrs..then didn't use until recently..I went to a genius bar and they acted like they didn't know what was wrong...after learning what I learned from that..I found out about the recall,,,even though I already was at a genius bar..do you think its worth while to send in via support section?

**Comment by glaszig** [comment]
i'd try at least. specifically mention you're suffering this defect: http://support.apple.com/kb/TS4088
